---
# Source: forecastle/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: forecastle
  labels:
    app: forecastle
    group: com.stakater.platform
    provider: stakater
    version: "0.0.14"
    chart: "forecastle-0.0.14"
    release: "RELEASE-NAME"
    heritage: "Tiller"
data:
  namespaces.conf: stakater
