apiVersion: apps/v1
kind: Deployment
metadata:
{{- if .Values.forecastle.deployment.annotations }}
  annotations:
{{ toYaml .Values.forecastle.deployment.annotations | indent 4 }}
{{- end }}
  labels:
{{ include "forecastle.labels.stakater" . | indent 4 }}
{{ include "forecastle.labels.chart" . | indent 4 }}
  name: {{ template "forecastle.name" . }}
spec:
  replicas: {{ .Values.forecastle.deployment.replicas }}
  revisionHistoryLimit: {{ .Values.forecastle.deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
{{ include "forecastle.labels.selector" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "forecastle.labels.selector" . | indent 8 }}
    spec:
      nodeSelector: {{- toYaml .Values.forecastle.deployment.nodeSelector | nindent 8 }}
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "{{ .Values.forecastle.image.name }}:{{ .Values.forecastle.image.tag }}"
        name: {{ template "forecastle.name" . }}
        volumeMounts:
        - name: {{ template "forecastle.name" . }}-config
          mountPath: /etc/forecastle
      volumes:
      - name: {{ template "forecastle.name" . }}-config
        configMap:
          name: {{ template "forecastle.name" . }}
      serviceAccountName: {{ template "forecastle.name" . }}
