apiVersion: extensions/v1beta1
kind: Deployment
metadata:
{{- if .Values.forecastle.deployment.annotations }}
  annotations:
{{ toYaml .Values.forecastle.deployment.annotations | indent 4 }}
{{- end }}
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: {{ template "name" . }}
spec:
  replicas: {{ .Values.forecastle.deployment.replicas }}
  revisionHistoryLimit: {{ .Values.forecastle.deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
{{ include "labels.selector" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "labels.selector" . | indent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "{{ .Values.forecastle.image.name }}:{{ .Values.forecastle.image.tag }}"
        name: {{ template "name" . }}
        volumeMounts:
        - name: {{ template "name" . }}-config
          mountPath: /etc/forecastle
    {{- if .Values.forecastle.proxy.enabled }}
      - name: proxy
        image: "{{ .Values.forecastle.proxy.image.name }}:{{ .Values.forecastle.proxy.image.tag }}"
        args:
        - --config={{ .Values.forecastle.proxy.args.config }}
        - --upstream-url={{ .Values.forecastle.proxy.args.upstreamUrl }}        
        volumeMounts:
        - name: keycloak-proxy-config
          mountPath: /etc/config
      volumes:
      - name: keycloak-proxy-config
        configMap:
          name: keycloak-proxy
      - name: {{ template "name" . }}-config
        configMap: 
          name: {{ template "name" . }}
    {{- else }}      
      volumes:      
      - name: {{ template "name" . }}-config
        configMap: 
          name: {{ template "name" . }}
    {{- end }}
      serviceAccountName: {{ template "name" . }}      
