---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
{{- if .Values.forecastle.service.annotations }}
    annotations:
{{ toYaml .Values.forecastle.service.annotations | indent 6 }}
{{- end }}
    labels:
{{ include "forecastle.labels.stakater" . | indent 6 }}
{{ include "forecastle.labels.chart" . | indent 6 }}
      expose: "{{ .Values.forecastle.service.expose }}"
    name: {{ template "forecastle.name" . }}
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
    selector:
{{ include "forecastle.labels.selector" . | indent 6 }}
