forecastle:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: "1.0.7"
  namespace: default
  image:
    name: stakater/forecastle
    tag: "1.0.7"
  deployment:
    replicas: 1
    revisionHistoryLimit: 2
  config:
    namespaces: "stakater"
  proxy:
    enabled: false
    image:
      name: quay.io/gambol99/keycloak-proxy
      tag: v2.1.1
    args:
      config: /etc/config/config.yml
      upstreamUrl: http://100.1.0.0:1234
  service:
    annotations:
      config.xposer.stakater.com/IngressURLPath: /
      config.xposer.stakater.com/Domain: stackator.com
      config.xposer.stakater.com/IngressNameTemplate: '<no value>-<no value>'
      config.xposer.stakater.com/IngressURLTemplate: '<no value>.<no value>.<no value>'
      config.xposer.stakater.com/TLS: "true"
      xposer.stakater.com/annotations: |-
        kubernetes.io/ingress.class: internal-ingress
        ingress.kubernetes.io/rewrite-target: /
        ingress.kubernetes.io/force-ssl-redirect: false
        certmanager.k8s.io/cluster-issuer: letsencrypt-production
    expose: "true"
