forecastle:
  createCustomResource: true
  labels:
    group: com.stakater.platform
    provider: stakater
    version: "v1.0.40"
  namespace: default
  image:
    name: stakater/forecastle
    tag: "v1.0.40"
  deployment:
    replicas: 1
    revisionHistoryLimit: 2
    annotations: {}
  config:
    namespaceSelector:
      matchNames:
      - stakater
    headerBackground:
    headerForeground:
    title:
    instanceName:
    customApps: {}
  proxy:
    enabled: false
  service:
    annotations: {}
    expose: "false"
  ingress:
    enabled: false
    annotations: {}
    hosts:
    - host: forecastle.example.com
      paths:
      - /